version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "ELASTIC_PASSWORD=password"
      - "xpack.security.enabled=true"
    volumes:
      - /home/zhuyiyi/docker-volume/elasticsearch/plugins/:/usr/share/elasticsearch/plugins/
      - /home/zhuyiyi/docker-volume/elasticsearch/data/:/usr/share/elasticsearch/data/
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=password"